version: "3"

services:
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - php_data:/php_data
        
    php:
        build:
            context: ./docker/php
        # user: "1000:1000"  -  // флаг запуска из-под юзера:группы
        volumes:
            - ./:/app
            - php_data:/tmp/data
            
volumes:
    php_data: